; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27027.1 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\jk\AppData\Local\Temp\.NETFramework,Version=v4.5.1.AssemblyAttributes.cpp"
